### ISSUE TITLE
cant find colorbrewer.json

### ISSUE THREAD

**Issue by steverweber** [timothyrenner/ColorBrewer.jl#10]
```
INFO: Precompiling module Vega...
ERROR: LoadError: SystemError: opening file /u/s8weber/.julia/v0.4/ColorBrewer/data/colorbrewer.json: No such file or directory
while loading /usr/local/share/julia/site/v0.4/ColorBrewer/src/ColorBrewer.jl, in expression starting on line 10
ERROR: LoadError: Failed to precompile ColorBrewer to /u/s8weber/.julia/lib/v0.4/ColorBrewer.ji
while loading /usr/local/share/julia/site/v0.4/Vega/src/Vega.jl, in expression starting on line 5
```

seems to use JULIA_PKGDIR but should loop over LOAD_PATH to find the file colorbrewer.json.

**Comment by timothyrenner** [comment]
Yes, the package looks for `colorbrewer.json` using `Pkg.dir("ColorBrewer")`. I'm a little confused as to why it's loaded in `/usr/local/share/julia/site/v0.4/ColorBrewer/` (please bear in mind that I'm hardly an "advanced" user).  Is there some special configuration for your environment?

**Comment by steverweber** [comment]
its related to:
https://github.com/randyzwitch/NoveltyColors.jl/issues/5#issuecomment-244235625

I'm deploying a large multi user system on some beefy hardware /university classrooms using shared hardware/ and want to share the julia package library with the users.

**Comment by steverweber** [comment]
julia dev said to use `dirname(@__FILE__)`

**Comment by timothyrenner** [comment]
Hey thanks for the tip - saved me tons of time! Give it a shot with the latest commit (0c21307393afe1868b9443bcbb16d52a4ad305f2) and let me know if that works.

**Comment by steverweber** [comment]
(wiped cache ~/.julia and rerun) confirmed to work. thanks!

**Comment by timothyrenner** [comment]
Fantastic! I'll try to get the fix merged into `METADATA.jl` some time in the next week.

**Comment by barche** [comment]
Could a new release with this fix please be tagged?

**Comment by timothyrenner** [comment]
Wow, I guess I totally forgot to do that last thing I said I would do. I'll get this done soon.

**Comment by timothyrenner** [comment]
Okay PR for the fix into METADATA.jl is open: https://github.com/JuliaLang/METADATA.jl/pull/10113
