### ISSUE TITLE
Continuous color schemes?

### ISSUE THREAD

**Issue by tlnagy** [timothyrenner/ColorBrewer.jl#9]
Is it possible to generate a continuous diverging color scheme to use with Gadfly?

**Comment by timothyrenner** [comment]
None of the ColorBrewer color schemes are defined as continuous. However, [Colors.jl](https://github.com/JuliaGraphics/Colors.jl) has a set of continuous diverging colormaps that should drop into Gadfly. I think you can also make your own color maps with that package as well.
